@startuml

class customers {
    +id: integer
    +first_name: string
    +last_name: string
    +phone: string
    +email: string
    +user_id: uuid
}

class agents {
    +id: integer
    +first_name: string
    +last_name: string
    +city: string
    +commission_percentage: numeric
    +user_id: uuid
}

class properties {
    +id: integer
    +operation_type: string
    +location: string
    +size: numeric
    +photos: bytea[]
    +owners: string
    +price: numeric
    +availability_status: string
    -agent_id: integer
    -customer_id: integer
}

class interested_customers {
    +id: integer
    -customer_id: integer
    -property_id: integer
    +deposit_amount: numeric
}

class customer_properties {
    +id: integer
    -customer_id: integer
    -property_id: integer
}

class property_transfers {
    +id: integer
    -property_id: integer
    -seller_id: integer
    -buyer_id: integer
    +transfer_date: date
    +sale_price: numeric
}

class attachments {
    +id: integer
    +model_name: string
    +model_id: integer
    +file_name: string
    +file_type: string
    +file_size: integer
    +url: string
}

customers --> agents
agents --> properties
customers --> interested_customers
customers --> customer_properties
properties --> property_transfers
attachments --> properties

@enduml
